steps:
# Execute Compile and Package
- name: maven:3.8.1
  id: compile-code
  entrypoint: mvn
  args: ["compile","package", "-Dmaven.test.skip=true"]
# Create Docker Image
- name: 'gcr.io/cloud-builders/docker'
  id: create-docker-image
  args: ['build', '--tag=gcr.io/$PROJECT_ID/${_IMAGE_NAME}', '--tag=gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID', '--tag=gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA' , '.']
# Push Docker  Image
- name: 'gcr.io/cloud-builders/docker'
  id: push-docker-image
  args: [ 'push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}']

#Update the container image using kubectl set
- name: 'gcr.io/cloud-builders/kubectl'
  id: update-GKE
  args: ['set', 'image', 'deployment/${_GKE_DEPLOYMENT_NAME}', '${_GKE_CONTAINER_NAME}=gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER_NAME}'

substitutions:
    _GKE_DEPLOYMENT_NAME: gke
    _GKE_CLUSTER_NAME: cost-optimized-cluster-1
    _ZONE: us-central1-c
    _IMAGE_NAME: gke
    _GKE_CONTAINER_NAME: compras-services-sha256-1
options:
   substitution_option: 'ALLOW_LOOSE'