apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke
  template:
    metadata:
      labels:
        app:gke
    spec:
      containers:
        - name: app
          image: gcr.io/digisprint-portals-test/gke-0.0.1-SNAPSHOT:latest
          imagePullPolicy: Always
