apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke
  template:
    metadata:
      labels:
        app:gke
    spec:
      containers:
        - name: app
          image: gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA
          imagePullPolicy: Always